/* soapBasicHttpBinding_USCOREPrimeAccountCloudServiceProxy.cpp
   Generated by gSOAP 2.8.34 for adas.h

gSOAP XML Web services tools
Copyright (C) 2000-2016, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#include "USCORECloudServiceProxy.h"

BasicHttpBinding_USCOREPrimeAccountCloudServiceProxy::BasicHttpBinding_USCOREPrimeAccountCloudServiceProxy() : soap(SOAP_IO_DEFAULT)
{	BasicHttpBinding_USCOREPrimeAccountCloudServiceProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

BasicHttpBinding_USCOREPrimeAccountCloudServiceProxy::BasicHttpBinding_USCOREPrimeAccountCloudServiceProxy(const BasicHttpBinding_USCOREPrimeAccountCloudServiceProxy& rhs)
{	soap_copy_context(this, &rhs);
	this->soap_endpoint = rhs.soap_endpoint;
}

BasicHttpBinding_USCOREPrimeAccountCloudServiceProxy::BasicHttpBinding_USCOREPrimeAccountCloudServiceProxy(const struct soap &_soap) : soap(_soap)
{ }

BasicHttpBinding_USCOREPrimeAccountCloudServiceProxy::BasicHttpBinding_USCOREPrimeAccountCloudServiceProxy(const char *endpoint) : soap(SOAP_IO_DEFAULT)
{	BasicHttpBinding_USCOREPrimeAccountCloudServiceProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
	soap_endpoint = endpoint;
}

BasicHttpBinding_USCOREPrimeAccountCloudServiceProxy::BasicHttpBinding_USCOREPrimeAccountCloudServiceProxy(soap_mode iomode) : soap(iomode)
{	BasicHttpBinding_USCOREPrimeAccountCloudServiceProxy_init(iomode, iomode);
}

BasicHttpBinding_USCOREPrimeAccountCloudServiceProxy::BasicHttpBinding_USCOREPrimeAccountCloudServiceProxy(const char *endpoint, soap_mode iomode) : soap(iomode)
{	BasicHttpBinding_USCOREPrimeAccountCloudServiceProxy_init(iomode, iomode);
	soap_endpoint = endpoint;
}

BasicHttpBinding_USCOREPrimeAccountCloudServiceProxy::BasicHttpBinding_USCOREPrimeAccountCloudServiceProxy(soap_mode imode, soap_mode omode) : soap(imode, omode)
{	BasicHttpBinding_USCOREPrimeAccountCloudServiceProxy_init(imode, omode);
}

BasicHttpBinding_USCOREPrimeAccountCloudServiceProxy::~BasicHttpBinding_USCOREPrimeAccountCloudServiceProxy()
{
	this->destroy();
	}

void BasicHttpBinding_USCOREPrimeAccountCloudServiceProxy::BasicHttpBinding_USCOREPrimeAccountCloudServiceProxy_init(soap_mode imode, soap_mode omode)
{	soap_imode(this, imode);
	soap_omode(this, omode);
	soap_endpoint = NULL;
	static const struct Namespace namespaces[] = {
        {"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://schemas.xmlsoap.org/soap/envelope/", NULL},
        {"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://schemas.xmlsoap.org/soap/encoding/", NULL},
        {"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
        {"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
        {"ns2", "http://www.vispect.com/SmartCarBaseLib/", NULL, NULL},
        {"arr", "http://schemas.microsoft.com/2003/10/Serialization/Arrays", NULL, NULL},
        {"ns1", "http://www.vispect.com/", NULL, NULL},
        {NULL, NULL, NULL, NULL}
    };
	soap_set_namespaces(this, namespaces);
}

#ifndef WITH_PURE_VIRTUAL
BasicHttpBinding_USCOREPrimeAccountCloudServiceProxy *BasicHttpBinding_USCOREPrimeAccountCloudServiceProxy::copy()
{	BasicHttpBinding_USCOREPrimeAccountCloudServiceProxy *dup = SOAP_NEW_COPY(BasicHttpBinding_USCOREPrimeAccountCloudServiceProxy(*(struct soap*)this));
	return dup;
}
#endif

BasicHttpBinding_USCOREPrimeAccountCloudServiceProxy& BasicHttpBinding_USCOREPrimeAccountCloudServiceProxy::operator=(const BasicHttpBinding_USCOREPrimeAccountCloudServiceProxy& rhs)
{	soap_copy_context(this, &rhs);
	this->soap_endpoint = rhs.soap_endpoint;
	return *this;
}

void BasicHttpBinding_USCOREPrimeAccountCloudServiceProxy::destroy()
{	soap_destroy(this);
	soap_end(this);
}

void BasicHttpBinding_USCOREPrimeAccountCloudServiceProxy::reset()
{	this->destroy();
	soap_done(this);
	soap_initialize(this);
	BasicHttpBinding_USCOREPrimeAccountCloudServiceProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

void BasicHttpBinding_USCOREPrimeAccountCloudServiceProxy::soap_noheader()
{	this->header = NULL;
}

::SOAP_ENV__Header *BasicHttpBinding_USCOREPrimeAccountCloudServiceProxy::soap_header()
{	return this->header;
}

::SOAP_ENV__Fault *BasicHttpBinding_USCOREPrimeAccountCloudServiceProxy::soap_fault()
{	return this->fault;
}

const char *BasicHttpBinding_USCOREPrimeAccountCloudServiceProxy::soap_fault_string()
{	return *soap_faultstring(this);
}

const char *BasicHttpBinding_USCOREPrimeAccountCloudServiceProxy::soap_fault_detail()
{	return *soap_faultdetail(this);
}

int BasicHttpBinding_USCOREPrimeAccountCloudServiceProxy::soap_close_socket()
{	return soap_closesock(this);
}

int BasicHttpBinding_USCOREPrimeAccountCloudServiceProxy::soap_force_close_socket()
{	return soap_force_closesock(this);
}

void BasicHttpBinding_USCOREPrimeAccountCloudServiceProxy::soap_print_fault(FILE *fd)
{	::soap_print_fault(this, fd);
}

#ifndef WITH_LEAN
#ifndef WITH_COMPAT
void BasicHttpBinding_USCOREPrimeAccountCloudServiceProxy::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this, os);
}
#endif

char *BasicHttpBinding_USCOREPrimeAccountCloudServiceProxy::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this, buf, len);
}
#endif

int BasicHttpBinding_USCOREPrimeAccountCloudServiceProxy::RegisterAccount(const char *endpoint, const char *soap_action, _ns1__RegisterAccount *ns1__RegisterAccount, _ns1__RegisterAccountResponse &ns1__RegisterAccountResponse)
{	struct soap *soap = this;
	struct __ns1__RegisterAccount soap_tmp___ns1__RegisterAccount;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://0.0.0.0:8000/SmartCarCloud/CarRunState http://0.0.0.0:8000/SmartCarCloud/PrimeAccount http://0.0.0.0:8000/SmartCarCloud/SmartDevice http://0.0.0.0:8000/SmartCarCloud/SmartWarn";
	if (soap_action == NULL)
		soap_action = "http://www.vispect.com/PrimeAccountCloudService/RegisterAccount";
	soap_tmp___ns1__RegisterAccount.ns1__RegisterAccount = ns1__RegisterAccount;
	soap_begin(soap);
	soap_set_version(soap, 1); /* SOAP1.1 */
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__RegisterAccount(soap, &soap_tmp___ns1__RegisterAccount);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__RegisterAccount(soap, &soap_tmp___ns1__RegisterAccount, "-ns1:RegisterAccount", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__RegisterAccount(soap, &soap_tmp___ns1__RegisterAccount, "-ns1:RegisterAccount", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns1__RegisterAccountResponse*>(&ns1__RegisterAccountResponse)) // NULL ref?
		return soap_closesock(soap);
	ns1__RegisterAccountResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__RegisterAccountResponse.soap_get(soap, "ns1:RegisterAccountResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int BasicHttpBinding_USCOREPrimeAccountCloudServiceProxy::UpdatePassWord(const char *endpoint, const char *soap_action, _ns1__UpdatePassWord *ns1__UpdatePassWord, _ns1__UpdatePassWordResponse &ns1__UpdatePassWordResponse)
{	struct soap *soap = this;
	struct __ns1__UpdatePassWord soap_tmp___ns1__UpdatePassWord;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://0.0.0.0:8000/SmartCarCloud/CarRunState http://0.0.0.0:8000/SmartCarCloud/PrimeAccount http://0.0.0.0:8000/SmartCarCloud/SmartDevice http://0.0.0.0:8000/SmartCarCloud/SmartWarn";
	if (soap_action == NULL)
		soap_action = "http://www.vispect.com/PrimeAccountCloudService/UpdatePassWord";
	soap_tmp___ns1__UpdatePassWord.ns1__UpdatePassWord = ns1__UpdatePassWord;
	soap_begin(soap);
	soap_set_version(soap, 1); /* SOAP1.1 */
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__UpdatePassWord(soap, &soap_tmp___ns1__UpdatePassWord);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__UpdatePassWord(soap, &soap_tmp___ns1__UpdatePassWord, "-ns1:UpdatePassWord", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__UpdatePassWord(soap, &soap_tmp___ns1__UpdatePassWord, "-ns1:UpdatePassWord", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns1__UpdatePassWordResponse*>(&ns1__UpdatePassWordResponse)) // NULL ref?
		return soap_closesock(soap);
	ns1__UpdatePassWordResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__UpdatePassWordResponse.soap_get(soap, "ns1:UpdatePassWordResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int BasicHttpBinding_USCOREPrimeAccountCloudServiceProxy::LoginCloud(const char *endpoint, const char *soap_action, _ns1__LoginCloud *ns1__LoginCloud, _ns1__LoginCloudResponse &ns1__LoginCloudResponse)
{	struct soap *soap = this;
	struct __ns1__LoginCloud soap_tmp___ns1__LoginCloud;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://0.0.0.0:8000/SmartCarCloud/CarRunState http://0.0.0.0:8000/SmartCarCloud/PrimeAccount http://0.0.0.0:8000/SmartCarCloud/SmartDevice http://0.0.0.0:8000/SmartCarCloud/SmartWarn";
	if (soap_action == NULL)
		soap_action = "http://www.vispect.com/PrimeAccountCloudService/LoginCloud";
	soap_tmp___ns1__LoginCloud.ns1__LoginCloud = ns1__LoginCloud;
	soap_begin(soap);
	soap_set_version(soap, 1); /* SOAP1.1 */
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__LoginCloud(soap, &soap_tmp___ns1__LoginCloud);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__LoginCloud(soap, &soap_tmp___ns1__LoginCloud, "-ns1:LoginCloud", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__LoginCloud(soap, &soap_tmp___ns1__LoginCloud, "-ns1:LoginCloud", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns1__LoginCloudResponse*>(&ns1__LoginCloudResponse)) // NULL ref?
		return soap_closesock(soap);
	ns1__LoginCloudResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__LoginCloudResponse.soap_get(soap, "ns1:LoginCloudResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int BasicHttpBinding_USCOREPrimeAccountCloudServiceProxy::GetAccount(const char *endpoint, const char *soap_action, _ns1__GetAccount *ns1__GetAccount, _ns1__GetAccountResponse &ns1__GetAccountResponse)
{	struct soap *soap = this;
	struct __ns1__GetAccount soap_tmp___ns1__GetAccount;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://0.0.0.0:8000/SmartCarCloud/CarRunState http://0.0.0.0:8000/SmartCarCloud/PrimeAccount http://0.0.0.0:8000/SmartCarCloud/SmartDevice http://0.0.0.0:8000/SmartCarCloud/SmartWarn";
	if (soap_action == NULL)
		soap_action = "http://www.vispect.com/PrimeAccountCloudService/GetAccount";
	soap_tmp___ns1__GetAccount.ns1__GetAccount = ns1__GetAccount;
	soap_begin(soap);
	soap_set_version(soap, 1); /* SOAP1.1 */
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__GetAccount(soap, &soap_tmp___ns1__GetAccount);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetAccount(soap, &soap_tmp___ns1__GetAccount, "-ns1:GetAccount", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetAccount(soap, &soap_tmp___ns1__GetAccount, "-ns1:GetAccount", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns1__GetAccountResponse*>(&ns1__GetAccountResponse)) // NULL ref?
		return soap_closesock(soap);
	ns1__GetAccountResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__GetAccountResponse.soap_get(soap, "ns1:GetAccountResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int BasicHttpBinding_USCOREPrimeAccountCloudServiceProxy::SelectAccount(const char *endpoint, const char *soap_action, _ns1__SelectAccount *ns1__SelectAccount, _ns1__SelectAccountResponse &ns1__SelectAccountResponse)
{	struct soap *soap = this;
	struct __ns1__SelectAccount soap_tmp___ns1__SelectAccount;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://0.0.0.0:8000/SmartCarCloud/CarRunState http://0.0.0.0:8000/SmartCarCloud/PrimeAccount http://0.0.0.0:8000/SmartCarCloud/SmartDevice http://0.0.0.0:8000/SmartCarCloud/SmartWarn";
	if (soap_action == NULL)
		soap_action = "http://www.vispect.com/PrimeAccountCloudService/SelectAccount";
	soap_tmp___ns1__SelectAccount.ns1__SelectAccount = ns1__SelectAccount;
	soap_begin(soap);
	soap_set_version(soap, 1); /* SOAP1.1 */
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__SelectAccount(soap, &soap_tmp___ns1__SelectAccount);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SelectAccount(soap, &soap_tmp___ns1__SelectAccount, "-ns1:SelectAccount", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SelectAccount(soap, &soap_tmp___ns1__SelectAccount, "-ns1:SelectAccount", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns1__SelectAccountResponse*>(&ns1__SelectAccountResponse)) // NULL ref?
		return soap_closesock(soap);
	ns1__SelectAccountResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__SelectAccountResponse.soap_get(soap, "ns1:SelectAccountResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int BasicHttpBinding_USCOREPrimeAccountCloudServiceProxy::SetAccount(const char *endpoint, const char *soap_action, _ns1__SetAccount *ns1__SetAccount, _ns1__SetAccountResponse &ns1__SetAccountResponse)
{	struct soap *soap = this;
	struct __ns1__SetAccount soap_tmp___ns1__SetAccount;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://0.0.0.0:8000/SmartCarCloud/CarRunState http://0.0.0.0:8000/SmartCarCloud/PrimeAccount http://0.0.0.0:8000/SmartCarCloud/SmartDevice http://0.0.0.0:8000/SmartCarCloud/SmartWarn";
	if (soap_action == NULL)
		soap_action = "http://www.vispect.com/PrimeAccountCloudService/SetAccount";
	soap_tmp___ns1__SetAccount.ns1__SetAccount = ns1__SetAccount;
	soap_begin(soap);
	soap_set_version(soap, 1); /* SOAP1.1 */
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__SetAccount(soap, &soap_tmp___ns1__SetAccount);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SetAccount(soap, &soap_tmp___ns1__SetAccount, "-ns1:SetAccount", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SetAccount(soap, &soap_tmp___ns1__SetAccount, "-ns1:SetAccount", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns1__SetAccountResponse*>(&ns1__SetAccountResponse)) // NULL ref?
		return soap_closesock(soap);
	ns1__SetAccountResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__SetAccountResponse.soap_get(soap, "ns1:SetAccountResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int BasicHttpBinding_USCOREPrimeAccountCloudServiceProxy::EditAccount(const char *endpoint, const char *soap_action, _ns1__EditAccount *ns1__EditAccount, _ns1__EditAccountResponse &ns1__EditAccountResponse)
{	struct soap *soap = this;
	struct __ns1__EditAccount soap_tmp___ns1__EditAccount;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://0.0.0.0:8000/SmartCarCloud/CarRunState http://0.0.0.0:8000/SmartCarCloud/PrimeAccount http://0.0.0.0:8000/SmartCarCloud/SmartDevice http://0.0.0.0:8000/SmartCarCloud/SmartWarn";
	if (soap_action == NULL)
		soap_action = "http://www.vispect.com/PrimeAccountCloudService/EditAccount";
	soap_tmp___ns1__EditAccount.ns1__EditAccount = ns1__EditAccount;
	soap_begin(soap);
	soap_set_version(soap, 1); /* SOAP1.1 */
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__EditAccount(soap, &soap_tmp___ns1__EditAccount);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__EditAccount(soap, &soap_tmp___ns1__EditAccount, "-ns1:EditAccount", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__EditAccount(soap, &soap_tmp___ns1__EditAccount, "-ns1:EditAccount", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns1__EditAccountResponse*>(&ns1__EditAccountResponse)) // NULL ref?
		return soap_closesock(soap);
	ns1__EditAccountResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__EditAccountResponse.soap_get(soap, "ns1:EditAccountResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int BasicHttpBinding_USCOREPrimeAccountCloudServiceProxy::CreateDevice(const char *endpoint, const char *soap_action, _ns1__CreateDevice *ns1__CreateDevice, _ns1__CreateDeviceResponse &ns1__CreateDeviceResponse)
{	struct soap *soap = this;
	struct __ns1__CreateDevice soap_tmp___ns1__CreateDevice;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://0.0.0.0:8000/SmartCarCloud/CarRunState http://0.0.0.0:8000/SmartCarCloud/PrimeAccount http://0.0.0.0:8000/SmartCarCloud/SmartDevice http://0.0.0.0:8000/SmartCarCloud/SmartWarn";
	if (soap_action == NULL)
		soap_action = "http://www.vispect.com/SmartDeviceCloudService/CreateDevice";
	soap_tmp___ns1__CreateDevice.ns1__CreateDevice = ns1__CreateDevice;
	soap_begin(soap);
	soap_set_version(soap, 1); /* SOAP1.1 */
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__CreateDevice(soap, &soap_tmp___ns1__CreateDevice);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__CreateDevice(soap, &soap_tmp___ns1__CreateDevice, "-ns1:CreateDevice", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__CreateDevice(soap, &soap_tmp___ns1__CreateDevice, "-ns1:CreateDevice", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns1__CreateDeviceResponse*>(&ns1__CreateDeviceResponse)) // NULL ref?
		return soap_closesock(soap);
	ns1__CreateDeviceResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__CreateDeviceResponse.soap_get(soap, "ns1:CreateDeviceResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int BasicHttpBinding_USCOREPrimeAccountCloudServiceProxy::MadeDevice(const char *endpoint, const char *soap_action, _ns1__MadeDevice *ns1__MadeDevice, _ns1__MadeDeviceResponse &ns1__MadeDeviceResponse)
{	struct soap *soap = this;
	struct __ns1__MadeDevice soap_tmp___ns1__MadeDevice;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://0.0.0.0:8000/SmartCarCloud/CarRunState http://0.0.0.0:8000/SmartCarCloud/PrimeAccount http://0.0.0.0:8000/SmartCarCloud/SmartDevice http://0.0.0.0:8000/SmartCarCloud/SmartWarn";
	if (soap_action == NULL)
		soap_action = "http://www.vispect.com/SmartDeviceCloudService/MadeDevice";
	soap_tmp___ns1__MadeDevice.ns1__MadeDevice = ns1__MadeDevice;
	soap_begin(soap);
	soap_set_version(soap, 1); /* SOAP1.1 */
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__MadeDevice(soap, &soap_tmp___ns1__MadeDevice);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__MadeDevice(soap, &soap_tmp___ns1__MadeDevice, "-ns1:MadeDevice", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__MadeDevice(soap, &soap_tmp___ns1__MadeDevice, "-ns1:MadeDevice", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns1__MadeDeviceResponse*>(&ns1__MadeDeviceResponse)) // NULL ref?
		return soap_closesock(soap);
	ns1__MadeDeviceResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__MadeDeviceResponse.soap_get(soap, "ns1:MadeDeviceResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int BasicHttpBinding_USCOREPrimeAccountCloudServiceProxy::SaleDevice(const char *endpoint, const char *soap_action, _ns1__SaleDevice *ns1__SaleDevice, _ns1__SaleDeviceResponse &ns1__SaleDeviceResponse)
{	struct soap *soap = this;
	struct __ns1__SaleDevice soap_tmp___ns1__SaleDevice;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://0.0.0.0:8000/SmartCarCloud/CarRunState http://0.0.0.0:8000/SmartCarCloud/PrimeAccount http://0.0.0.0:8000/SmartCarCloud/SmartDevice http://0.0.0.0:8000/SmartCarCloud/SmartWarn";
	if (soap_action == NULL)
		soap_action = "http://www.vispect.com/SmartDeviceCloudService/SaleDevice";
	soap_tmp___ns1__SaleDevice.ns1__SaleDevice = ns1__SaleDevice;
	soap_begin(soap);
	soap_set_version(soap, 1); /* SOAP1.1 */
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__SaleDevice(soap, &soap_tmp___ns1__SaleDevice);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SaleDevice(soap, &soap_tmp___ns1__SaleDevice, "-ns1:SaleDevice", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SaleDevice(soap, &soap_tmp___ns1__SaleDevice, "-ns1:SaleDevice", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns1__SaleDeviceResponse*>(&ns1__SaleDeviceResponse)) // NULL ref?
		return soap_closesock(soap);
	ns1__SaleDeviceResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__SaleDeviceResponse.soap_get(soap, "ns1:SaleDeviceResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int BasicHttpBinding_USCOREPrimeAccountCloudServiceProxy::BindingDevice(const char *endpoint, const char *soap_action, _ns1__BindingDevice *ns1__BindingDevice, _ns1__BindingDeviceResponse &ns1__BindingDeviceResponse)
{	struct soap *soap = this;
	struct __ns1__BindingDevice soap_tmp___ns1__BindingDevice;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://0.0.0.0:8000/SmartCarCloud/CarRunState http://0.0.0.0:8000/SmartCarCloud/PrimeAccount http://0.0.0.0:8000/SmartCarCloud/SmartDevice http://0.0.0.0:8000/SmartCarCloud/SmartWarn";
	if (soap_action == NULL)
		soap_action = "http://www.vispect.com/SmartDeviceCloudService/BindingDevice";
	soap_tmp___ns1__BindingDevice.ns1__BindingDevice = ns1__BindingDevice;
	soap_begin(soap);
	soap_set_version(soap, 1); /* SOAP1.1 */
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__BindingDevice(soap, &soap_tmp___ns1__BindingDevice);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__BindingDevice(soap, &soap_tmp___ns1__BindingDevice, "-ns1:BindingDevice", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__BindingDevice(soap, &soap_tmp___ns1__BindingDevice, "-ns1:BindingDevice", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns1__BindingDeviceResponse*>(&ns1__BindingDeviceResponse)) // NULL ref?
		return soap_closesock(soap);
	ns1__BindingDeviceResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__BindingDeviceResponse.soap_get(soap, "ns1:BindingDeviceResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int BasicHttpBinding_USCOREPrimeAccountCloudServiceProxy::GetDevice(const char *endpoint, const char *soap_action, _ns1__GetDevice *ns1__GetDevice, _ns1__GetDeviceResponse &ns1__GetDeviceResponse)
{	struct soap *soap = this;
	struct __ns1__GetDevice soap_tmp___ns1__GetDevice;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://0.0.0.0:8000/SmartCarCloud/CarRunState http://0.0.0.0:8000/SmartCarCloud/PrimeAccount http://0.0.0.0:8000/SmartCarCloud/SmartDevice http://0.0.0.0:8000/SmartCarCloud/SmartWarn";
	if (soap_action == NULL)
		soap_action = "http://www.vispect.com/SmartDeviceCloudService/GetDevice";
	soap_tmp___ns1__GetDevice.ns1__GetDevice = ns1__GetDevice;
	soap_begin(soap);
	soap_set_version(soap, 1); /* SOAP1.1 */
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__GetDevice(soap, &soap_tmp___ns1__GetDevice);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetDevice(soap, &soap_tmp___ns1__GetDevice, "-ns1:GetDevice", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetDevice(soap, &soap_tmp___ns1__GetDevice, "-ns1:GetDevice", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns1__GetDeviceResponse*>(&ns1__GetDeviceResponse)) // NULL ref?
		return soap_closesock(soap);
	ns1__GetDeviceResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__GetDeviceResponse.soap_get(soap, "ns1:GetDeviceResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int BasicHttpBinding_USCOREPrimeAccountCloudServiceProxy::SendSmartWarn(const char *endpoint, const char *soap_action, _ns1__SendSmartWarn *ns1__SendSmartWarn, _ns1__SendSmartWarnResponse &ns1__SendSmartWarnResponse)
{	struct soap *soap = this;
	struct __ns1__SendSmartWarn soap_tmp___ns1__SendSmartWarn;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://0.0.0.0:8000/SmartCarCloud/CarRunState http://0.0.0.0:8000/SmartCarCloud/PrimeAccount http://0.0.0.0:8000/SmartCarCloud/SmartDevice http://0.0.0.0:8000/SmartCarCloud/SmartWarn";
	if (soap_action == NULL)
		soap_action = "http://www.vispect.com/SmartWarnCloudService/SendSmartWarn";
	soap_tmp___ns1__SendSmartWarn.ns1__SendSmartWarn = ns1__SendSmartWarn;
	soap_begin(soap);
	soap_set_version(soap, 1); /* SOAP1.1 */
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__SendSmartWarn(soap, &soap_tmp___ns1__SendSmartWarn);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SendSmartWarn(soap, &soap_tmp___ns1__SendSmartWarn, "-ns1:SendSmartWarn", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SendSmartWarn(soap, &soap_tmp___ns1__SendSmartWarn, "-ns1:SendSmartWarn", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns1__SendSmartWarnResponse*>(&ns1__SendSmartWarnResponse)) // NULL ref?
		return soap_closesock(soap);
	ns1__SendSmartWarnResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__SendSmartWarnResponse.soap_get(soap, "ns1:SendSmartWarnResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int BasicHttpBinding_USCOREPrimeAccountCloudServiceProxy::PostListSmartWarn(const char *endpoint, const char *soap_action, _ns1__PostListSmartWarn *ns1__PostListSmartWarn, _ns1__PostListSmartWarnResponse &ns1__PostListSmartWarnResponse)
{	struct soap *soap = this;
	struct __ns1__PostListSmartWarn soap_tmp___ns1__PostListSmartWarn;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://0.0.0.0:8000/SmartCarCloud/CarRunState http://0.0.0.0:8000/SmartCarCloud/PrimeAccount http://0.0.0.0:8000/SmartCarCloud/SmartDevice http://0.0.0.0:8000/SmartCarCloud/SmartWarn";
	if (soap_action == NULL)
		soap_action = "http://www.vispect.com/SmartWarnCloudService/PostListSmartWarn";
	soap_tmp___ns1__PostListSmartWarn.ns1__PostListSmartWarn = ns1__PostListSmartWarn;
	soap_begin(soap);
	soap_set_version(soap, 1); /* SOAP1.1 */
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__PostListSmartWarn(soap, &soap_tmp___ns1__PostListSmartWarn);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__PostListSmartWarn(soap, &soap_tmp___ns1__PostListSmartWarn, "-ns1:PostListSmartWarn", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__PostListSmartWarn(soap, &soap_tmp___ns1__PostListSmartWarn, "-ns1:PostListSmartWarn", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns1__PostListSmartWarnResponse*>(&ns1__PostListSmartWarnResponse)) // NULL ref?
		return soap_closesock(soap);
	ns1__PostListSmartWarnResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__PostListSmartWarnResponse.soap_get(soap, "ns1:PostListSmartWarnResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int BasicHttpBinding_USCOREPrimeAccountCloudServiceProxy::GetSmartWarn(const char *endpoint, const char *soap_action, _ns1__GetSmartWarn *ns1__GetSmartWarn, _ns1__GetSmartWarnResponse &ns1__GetSmartWarnResponse)
{	struct soap *soap = this;
	struct __ns1__GetSmartWarn soap_tmp___ns1__GetSmartWarn;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://0.0.0.0:8000/SmartCarCloud/CarRunState http://0.0.0.0:8000/SmartCarCloud/PrimeAccount http://0.0.0.0:8000/SmartCarCloud/SmartDevice http://0.0.0.0:8000/SmartCarCloud/SmartWarn";
	if (soap_action == NULL)
		soap_action = "http://www.vispect.com/SmartWarnCloudService/GetSmartWarn";
	soap_tmp___ns1__GetSmartWarn.ns1__GetSmartWarn = ns1__GetSmartWarn;
	soap_begin(soap);
	soap_set_version(soap, 1); /* SOAP1.1 */
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__GetSmartWarn(soap, &soap_tmp___ns1__GetSmartWarn);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetSmartWarn(soap, &soap_tmp___ns1__GetSmartWarn, "-ns1:GetSmartWarn", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetSmartWarn(soap, &soap_tmp___ns1__GetSmartWarn, "-ns1:GetSmartWarn", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns1__GetSmartWarnResponse*>(&ns1__GetSmartWarnResponse)) // NULL ref?
		return soap_closesock(soap);
	ns1__GetSmartWarnResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__GetSmartWarnResponse.soap_get(soap, "ns1:GetSmartWarnResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int BasicHttpBinding_USCOREPrimeAccountCloudServiceProxy::TotalSmartWarn(const char *endpoint, const char *soap_action, _ns1__TotalSmartWarn *ns1__TotalSmartWarn, _ns1__TotalSmartWarnResponse &ns1__TotalSmartWarnResponse)
{	struct soap *soap = this;
	struct __ns1__TotalSmartWarn soap_tmp___ns1__TotalSmartWarn;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://0.0.0.0:8000/SmartCarCloud/CarRunState http://0.0.0.0:8000/SmartCarCloud/PrimeAccount http://0.0.0.0:8000/SmartCarCloud/SmartDevice http://0.0.0.0:8000/SmartCarCloud/SmartWarn";
	if (soap_action == NULL)
		soap_action = "http://www.vispect.com/SmartWarnCloudService/TotalSmartWarn";
	soap_tmp___ns1__TotalSmartWarn.ns1__TotalSmartWarn = ns1__TotalSmartWarn;
	soap_begin(soap);
	soap_set_version(soap, 1); /* SOAP1.1 */
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__TotalSmartWarn(soap, &soap_tmp___ns1__TotalSmartWarn);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__TotalSmartWarn(soap, &soap_tmp___ns1__TotalSmartWarn, "-ns1:TotalSmartWarn", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__TotalSmartWarn(soap, &soap_tmp___ns1__TotalSmartWarn, "-ns1:TotalSmartWarn", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns1__TotalSmartWarnResponse*>(&ns1__TotalSmartWarnResponse)) // NULL ref?
		return soap_closesock(soap);
	ns1__TotalSmartWarnResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__TotalSmartWarnResponse.soap_get(soap, "ns1:TotalSmartWarnResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int BasicHttpBinding_USCOREPrimeAccountCloudServiceProxy::SendCarRunState(const char *endpoint, const char *soap_action, _ns1__SendCarRunState *ns1__SendCarRunState, _ns1__SendCarRunStateResponse &ns1__SendCarRunStateResponse)
{	struct soap *soap = this;
	struct __ns1__SendCarRunState soap_tmp___ns1__SendCarRunState;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://0.0.0.0:8000/SmartCarCloud/CarRunState http://0.0.0.0:8000/SmartCarCloud/PrimeAccount http://0.0.0.0:8000/SmartCarCloud/SmartDevice http://0.0.0.0:8000/SmartCarCloud/SmartWarn";
	if (soap_action == NULL)
		soap_action = "http://www.vispect.com/CarRunStateCloudService/SendCarRunState";
	soap_tmp___ns1__SendCarRunState.ns1__SendCarRunState = ns1__SendCarRunState;
	soap_begin(soap);
	soap_set_version(soap, 1); /* SOAP1.1 */
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__SendCarRunState(soap, &soap_tmp___ns1__SendCarRunState);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SendCarRunState(soap, &soap_tmp___ns1__SendCarRunState, "-ns1:SendCarRunState", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SendCarRunState(soap, &soap_tmp___ns1__SendCarRunState, "-ns1:SendCarRunState", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns1__SendCarRunStateResponse*>(&ns1__SendCarRunStateResponse)) // NULL ref?
		return soap_closesock(soap);
	ns1__SendCarRunStateResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__SendCarRunStateResponse.soap_get(soap, "ns1:SendCarRunStateResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int BasicHttpBinding_USCOREPrimeAccountCloudServiceProxy::PostListCarRunState(const char *endpoint, const char *soap_action, _ns1__PostListCarRunState *ns1__PostListCarRunState, _ns1__PostListCarRunStateResponse &ns1__PostListCarRunStateResponse)
{	struct soap *soap = this;
	struct __ns1__PostListCarRunState soap_tmp___ns1__PostListCarRunState;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://0.0.0.0:8000/SmartCarCloud/CarRunState http://0.0.0.0:8000/SmartCarCloud/PrimeAccount http://0.0.0.0:8000/SmartCarCloud/SmartDevice http://0.0.0.0:8000/SmartCarCloud/SmartWarn";
	if (soap_action == NULL)
		soap_action = "http://www.vispect.com/CarRunStateCloudService/PostListCarRunState";
	soap_tmp___ns1__PostListCarRunState.ns1__PostListCarRunState = ns1__PostListCarRunState;
	soap_begin(soap);
	soap_set_version(soap, 1); /* SOAP1.1 */
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__PostListCarRunState(soap, &soap_tmp___ns1__PostListCarRunState);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__PostListCarRunState(soap, &soap_tmp___ns1__PostListCarRunState, "-ns1:PostListCarRunState", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__PostListCarRunState(soap, &soap_tmp___ns1__PostListCarRunState, "-ns1:PostListCarRunState", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns1__PostListCarRunStateResponse*>(&ns1__PostListCarRunStateResponse)) // NULL ref?
		return soap_closesock(soap);
	ns1__PostListCarRunStateResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__PostListCarRunStateResponse.soap_get(soap, "ns1:PostListCarRunStateResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int BasicHttpBinding_USCOREPrimeAccountCloudServiceProxy::GetCarRunState(const char *endpoint, const char *soap_action, _ns1__GetCarRunState *ns1__GetCarRunState, _ns1__GetCarRunStateResponse &ns1__GetCarRunStateResponse)
{	struct soap *soap = this;
	struct __ns1__GetCarRunState soap_tmp___ns1__GetCarRunState;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://0.0.0.0:8000/SmartCarCloud/CarRunState http://0.0.0.0:8000/SmartCarCloud/PrimeAccount http://0.0.0.0:8000/SmartCarCloud/SmartDevice http://0.0.0.0:8000/SmartCarCloud/SmartWarn";
	if (soap_action == NULL)
		soap_action = "http://www.vispect.com/CarRunStateCloudService/GetCarRunState";
	soap_tmp___ns1__GetCarRunState.ns1__GetCarRunState = ns1__GetCarRunState;
	soap_begin(soap);
	soap_set_version(soap, 1); /* SOAP1.1 */
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__GetCarRunState(soap, &soap_tmp___ns1__GetCarRunState);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetCarRunState(soap, &soap_tmp___ns1__GetCarRunState, "-ns1:GetCarRunState", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetCarRunState(soap, &soap_tmp___ns1__GetCarRunState, "-ns1:GetCarRunState", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns1__GetCarRunStateResponse*>(&ns1__GetCarRunStateResponse)) // NULL ref?
		return soap_closesock(soap);
	ns1__GetCarRunStateResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__GetCarRunStateResponse.soap_get(soap, "ns1:GetCarRunStateResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
/* End of client proxy code */
